# Generated by Django 5.1.3 on 2026-01-03 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PlaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "通所"), (8, "在宅"), (9, "休み")], default=9
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_record",
                        to="app.customermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerWorkStatusPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "通所"), (8, "在宅"), (9, "休み")], default=9
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="OperationLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("target_model", models.CharField(blank=True, max_length=50)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "diff",
                    models.JSONField(blank=True, help_text="更新前後の差分", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSessionRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "current_status",
                    models.IntegerField(
                        choices=[
                            (0, "通所前"),
                            (1, "勤務中"),
                            (5, "退勤"),
                            (7, "移動済"),
                            (8, "在宅"),
                            (9, "休み"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_session_record",
                        to="app.customerrecordmodel",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.placemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["session_no"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSessionPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_session_pattern",
                        to="app.customermodel",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.placemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceRemarksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                ("remarks", models.CharField(blank=True, default="", max_length=100)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.placemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (10, "有給")], default=9
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_record",
                        to="app.staffmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffSessionPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.placemodel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_session_pattern",
                        to="app.staffmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffSessionRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "current_status",
                    models.IntegerField(
                        choices=[
                            (0, "出勤前"),
                            (1, "勤務中"),
                            (5, "退勤"),
                            (7, "移動済"),
                            (9, "休み"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.placemodel",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_session_record",
                        to="app.staffrecordmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["session_no"],
            },
        ),
        migrations.CreateModel(
            name="StaffWorkStatusPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (10, "有給")], default=9
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.staffmodel"
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="TransportPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.IntegerField(choices=[(1, "朝"), (2, "帰り")]),
                ),
                (
                    "transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "送迎"),
                            (2, "車"),
                            (3, "バス"),
                            (4, "自転車"),
                            (5, "徒歩"),
                            (6, "バイク"),
                            (9, "その他"),
                        ],
                        null=True,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=20, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.staffmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="TransportRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.IntegerField(choices=[(1, "朝"), (2, "帰り")]),
                ),
                (
                    "transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "送迎"),
                            (2, "車"),
                            (3, "バス"),
                            (4, "自転車"),
                            (5, "徒歩"),
                            (6, "バイク"),
                            (9, "その他"),
                        ],
                        null=True,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=20, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_transport",
                        to="app.customerrecordmodel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.staffmodel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="customerrecordmodel",
            constraint=models.UniqueConstraint(
                fields=("customer", "work_date"), name="unique_customer_work_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerworkstatuspatternmodel",
            unique_together={("customer", "weekday")},
        ),
        migrations.AlterUniqueTogether(
            name="customersessionrecordmodel",
            unique_together={("record", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="customersessionpatternmodel",
            unique_together={("customer", "weekday", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="placeremarksmodel",
            unique_together={("place", "work_date")},
        ),
        migrations.AddConstraint(
            model_name="staffrecordmodel",
            constraint=models.UniqueConstraint(
                fields=("staff", "work_date"), name="unique_staff_work_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffsessionpatternmodel",
            unique_together={("staff", "weekday", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="staffsessionrecordmodel",
            unique_together={("record", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="staffworkstatuspatternmodel",
            unique_together={("staff", "weekday")},
        ),
        migrations.AlterUniqueTogether(
            name="transportpatternmodel",
            unique_together={("customer", "weekday", "transport_type")},
        ),
        migrations.AlterUniqueTogether(
            name="transportrecordmodel",
            unique_together={("record", "transport_type")},
        ),
    ]
