# Generated by Django 5.1.3 on 2026-01-01 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PlaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "通所"), (8, "在宅"), (9, "休み")], default=9
                    ),
                ),
                (
                    "current_status",
                    models.IntegerField(
                        choices=[
                            (0, "通所前"),
                            (1, "通所中"),
                            (5, "退勤"),
                            (8, "在宅"),
                            (9, "休み"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.customermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["customer__order"],
            },
        ),
        migrations.CreateModel(
            name="CustomerWorkStatusPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "通所"), (8, "在宅"), (9, "休み")], default=9
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_work_status_pattern",
                        to="app.customermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="LogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateTime", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerSessionRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_session_record",
                        to="app.customerrecordmodel",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.placemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["session_no"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSessionPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_session_pattern",
                        to="app.customermodel",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.placemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceRemarksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                ("remarks", models.CharField(blank=True, default="", max_length=100)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.placemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("order", models.IntegerField()),
                (
                    "work_status_mon",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                (
                    "work_status_tue",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                (
                    "work_status_wed",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                (
                    "work_status_thu",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                (
                    "work_status_fri",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                (
                    "work_status_sat",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                (
                    "work_status_sun",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=1
                    ),
                ),
                ("work1_start_time", models.TimeField(blank=True, null=True)),
                ("work1_end_time", models.TimeField(blank=True, null=True)),
                ("work2_start_time", models.TimeField(blank=True, null=True)),
                ("work2_end_time", models.TimeField(blank=True, null=True)),
                ("work3_start_time", models.TimeField(blank=True, null=True)),
                ("work3_end_time", models.TimeField(blank=True, null=True)),
                (
                    "work1_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_work1_place",
                        to="app.placemodel",
                    ),
                ),
                (
                    "work2_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_work2_place",
                        to="app.placemodel",
                    ),
                ),
                (
                    "work3_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_work3_place",
                        to="app.placemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StaffWorkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=9
                    ),
                ),
                ("work1_start_time", models.TimeField(blank=True, null=True)),
                ("work1_end_time", models.TimeField(blank=True, null=True)),
                ("work2_start_time", models.TimeField(blank=True, null=True)),
                ("work2_end_time", models.TimeField(blank=True, null=True)),
                ("work3_start_time", models.TimeField(blank=True, null=True)),
                ("work3_end_time", models.TimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="app.staffmodel",
                    ),
                ),
                (
                    "work1_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work1_place",
                        to="app.placemodel",
                    ),
                ),
                (
                    "work2_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work2_place",
                        to="app.placemodel",
                    ),
                ),
                (
                    "work3_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work3_place",
                        to="app.placemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["staff__order"],
            },
        ),
        migrations.CreateModel(
            name="TransportPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.IntegerField(choices=[(1, "朝"), (2, "帰り")]),
                ),
                (
                    "transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "送迎"),
                            (2, "車"),
                            (3, "バス"),
                            (4, "自転車"),
                            (5, "徒歩"),
                            (6, "バイク"),
                            (9, "その他"),
                        ],
                        null=True,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=20, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.staffmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="TransportRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.IntegerField(choices=[(1, "朝"), (2, "帰り")]),
                ),
                (
                    "transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "送迎"),
                            (2, "車"),
                            (3, "バス"),
                            (4, "自転車"),
                            (5, "徒歩"),
                            (6, "バイク"),
                            (9, "その他"),
                        ],
                        null=True,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=20, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_transport",
                        to="app.customerrecordmodel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.staffmodel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="customerrecordmodel",
            constraint=models.UniqueConstraint(
                fields=("customer", "work_date"), name="unique_customer_work_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerworkstatuspatternmodel",
            unique_together={("customer", "weekday")},
        ),
        migrations.AlterUniqueTogether(
            name="customersessionrecordmodel",
            unique_together={("record", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="customersessionpatternmodel",
            unique_together={("customer", "weekday", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="placeremarksmodel",
            unique_together={("place", "work_date")},
        ),
        migrations.AlterUniqueTogether(
            name="staffworkmodel",
            unique_together={("staff", "work_date")},
        ),
        migrations.AlterUniqueTogether(
            name="transportpatternmodel",
            unique_together={("customer", "weekday", "transport_type")},
        ),
        migrations.AlterUniqueTogether(
            name="transportrecordmodel",
            unique_together={("record", "transport_type")},
        ),
    ]
