# Generated by Django 5.1.3 on 2026-01-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "通所"), (8, "在宅"), (9, "休み")], default=9
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "unique_together": {("customer", "weekday")},
            },
        ),
        migrations.CreateModel(
            name="StaffPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (10, "有給")], default=9
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.staffmodel"
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "unique_together": {("staff", "weekday")},
            },
        ),
    ]
