# Generated by Django 5.1.3 on 2026-01-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportpatternmodel",
            name="time",
        ),
        migrations.RemoveField(
            model_name="transportrecordmodel",
            name="time",
        ),
        migrations.AddField(
            model_name="transportpatternmodel",
            name="remarks",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="transportrecordmodel",
            name="remarks",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
