# Generated by Django 5.1.3 on 2026-01-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersessionpatternmodel",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.placemodel",
            ),
        ),
        migrations.AlterField(
            model_name="customersessionrecordmodel",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.placemodel",
            ),
        ),
        migrations.AlterField(
            model_name="customerworkstatuspatternmodel",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.customermodel"
            ),
        ),
        migrations.CreateModel(
            name="CustomerWorkStatusRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "通所"), (8, "在宅"), (9, "休み")], default=9
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customermodel",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customerrecordmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("record", "customer")},
            },
        ),
    ]
