# Generated by Django 5.1.3 on 2026-01-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_transportpatternmodel_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffrecordmodel",
            name="change_history",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
