# Generated by Django 5.1.3 on 2026-01-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customerpatternmodel_staffpatternmodel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffworkstatuspatternmodel",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="staffworkstatuspatternmodel",
            name="staff",
        ),
        migrations.DeleteModel(
            name="CustomerWorkStatusPatternModel",
        ),
        migrations.DeleteModel(
            name="StaffWorkStatusPatternModel",
        ),
    ]
