# Generated by Django 5.1.1 on 2024-12-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_arearemarks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AreaRemarks",
            new_name="AreaRemarksModel",
        ),
    ]
