# Generated by Django 5.1.3 on 2026-01-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_customersessionpatternmodel_place_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffworkmodel",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="staffworkmodel",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="staffworkmodel",
            name="work1_place",
        ),
        migrations.RemoveField(
            model_name="staffworkmodel",
            name="work2_place",
        ),
        migrations.RemoveField(
            model_name="staffworkmodel",
            name="work3_place",
        ),
        migrations.AlterModelOptions(
            name="customerrecordmodel",
            options={},
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work1_end_time",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work1_place",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work1_start_time",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work2_end_time",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work2_place",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work2_start_time",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work3_end_time",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work3_place",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work3_start_time",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_fri",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_mon",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_sat",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_sun",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_thu",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_tue",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="work_status_wed",
        ),
        migrations.AlterField(
            model_name="customerrecordmodel",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_record",
                to="app.customermodel",
            ),
        ),
        migrations.CreateModel(
            name="StaffRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=9
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_record",
                        to="app.staffmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffSessionPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.placemodel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_session_pattern",
                        to="app.staffmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffSessionRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField(default=1)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.placemodel",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_session_record",
                        to="app.staffrecordmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["session_no"],
            },
        ),
        migrations.CreateModel(
            name="StaffWorkStatusPatternModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "月"),
                            (2, "火"),
                            (3, "水"),
                            (4, "木"),
                            (5, "金"),
                            (6, "土"),
                            (7, "日"),
                        ]
                    ),
                ),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(1, "出勤"), (9, "欠勤"), (8, "有給")], default=9
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.staffmodel"
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.DeleteModel(
            name="CustomerWorkStatusRecordModel",
        ),
        migrations.DeleteModel(
            name="StaffWorkModel",
        ),
        migrations.AddConstraint(
            model_name="staffrecordmodel",
            constraint=models.UniqueConstraint(
                fields=("staff", "work_date"), name="unique_staff_work_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffsessionpatternmodel",
            unique_together={("staff", "weekday", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="staffsessionrecordmodel",
            unique_together={("record", "session_no")},
        ),
        migrations.AlterUniqueTogether(
            name="staffworkstatuspatternmodel",
            unique_together={("staff", "weekday")},
        ),
    ]
