# Generated by Django 5.1.3 on 2026-01-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_staffworkstatuspatternmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysAdModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_mode_days", models.IntegerField(default=0)),
            ],
        ),
    ]
