# Generated by Django 5.1.1 on 2024-12-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_arearemarks_arearemarksmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AreaRemarksModel",
            new_name="PlaceRemarksModel",
        ),
    ]
