# Generated by Django 5.1.3 on 2026-01-04 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_staffrecordmodel_change_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffrecordmodel",
            options={"ordering": ["staff__order"]},
        ),
        migrations.AddField(
            model_name="customerrecordmodel",
            name="change_history",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customerrecordmodel",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_records",
                to="app.customermodel",
            ),
        ),
        migrations.AlterField(
            model_name="staffrecordmodel",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_records",
                to="app.staffmodel",
            ),
        ),
    ]
