# Generated by Django 5.1.3 on 2026-01-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_staffworkmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerrecordmodel",
            name="current_status",
        ),
    ]
