# Generated by Django 5.1.3 on 2026-01-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_staffrecordmodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerrecordmodel",
            name="change_history",
        ),
        migrations.RemoveField(
            model_name="staffrecordmodel",
            name="change_history",
        ),
        migrations.AddField(
            model_name="customerrecordmodel",
            name="work_status_change_history",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="work_status_change_history",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customerrecordmodel",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_records",
                to="app.customermodel",
            ),
        ),
        migrations.AlterField(
            model_name="placemodel",
            name="name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="staffrecordmodel",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_records",
                to="app.staffmodel",
            ),
        ),
        migrations.AlterField(
            model_name="transportpatternmodel",
            name="place",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="transportpatternmodel",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="transportrecordmodel",
            name="place",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="transportrecordmodel",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
