# Generated by Django 5.1.1 on 2024-12-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_arearemarksmodel_placeremarksmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="placeremarksmodel",
            old_name="area",
            new_name="place",
        ),
        migrations.AlterUniqueTogether(
            name="placeremarksmodel",
            unique_together={("place", "work_date")},
        ),
    ]
