# Generated by Django 5.1.3 on 2026-01-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_staffrecordmodel_staff_operationlogmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlogmodel",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
