# Generated by Django 5.1.1 on 2024-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_area_placeremarksmodel_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeremarksmodel",
            name="remarks",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
