# Generated by Django 5.1.3 on 2026-01-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_customerpatternmodel_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpatternmodel",
            name="remarks",
            field=models.TextField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customerrecordmodel",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="staffpatternmodel",
            name="remarks",
            field=models.TextField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="staffrecordmodel",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
