# Generated by Django 5.1.3 on 2026-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_customerrecordmodel_change_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrecordmodel",
            name="change_history",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="change_history",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
