# Generated by Django 5.1.3 on 2026-01-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_operationlogmodel_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationlogmodel",
            name="ip_address",
        ),
    ]
