# Generated by Django 5.1.3 on 2026-01-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_customerrecordmodel_change_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerrecordmodel",
            name="work_status_change_history",
        ),
        migrations.RemoveField(
            model_name="staffrecordmodel",
            name="work_status_change_history",
        ),
    ]
