# Generated by Django 5.1.3 on 2026-01-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_operationlogmodel_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersessionrecordmodel",
            name="current_status",
            field=models.IntegerField(
                choices=[
                    (0, "通所前"),
                    (1, "勤務中"),
                    (5, "退勤"),
                    (7, "移動済"),
                    (8, "在宅"),
                    (9, "休み"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="staffsessionrecordmodel",
            name="current_status",
            field=models.IntegerField(
                choices=[
                    (0, "出勤前"),
                    (1, "勤務中"),
                    (5, "退勤"),
                    (7, "移動済"),
                    (9, "休み"),
                ],
                default=0,
            ),
        ),
    ]
