# Generated by Django 5.1.3 on 2026-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_customerrecordmodel_remarks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customersessionrecordmodel",
            name="current_status",
        ),
        migrations.RemoveField(
            model_name="staffsessionrecordmodel",
            name="current_status",
        ),
        migrations.AddField(
            model_name="customerrecordmodel",
            name="current_status",
            field=models.IntegerField(
                choices=[
                    (0, "通所前"),
                    (1, "勤務中"),
                    (5, "退勤済"),
                    (7, "移動済"),
                    (8, "在宅"),
                    (9, "休み"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="customerrecordmodel",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrecordmodel",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="current_status",
            field=models.IntegerField(
                choices=[
                    (0, "出勤前"),
                    (1, "勤務中"),
                    (5, "退勤済"),
                    (7, "移動済"),
                    (9, "休み"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
