# Generated by Django 5.1.3 on 2026-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_customerrecordmodel_work_status_change_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrecordmodel",
            name="work_status_change_history",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="work_status_change_history",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
