# Generated by Django 5.1.3 on 2025-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_placeremarksmodel_remarks_logmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycarmodel",
            name="test",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
