# Generated by Django 5.1.3 on 2026-01-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_customersessionrecordmodel_current_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerrecordmodel",
            old_name="start_time",
            new_name="clock_in_time",
        ),
        migrations.RenameField(
            model_name="customerrecordmodel",
            old_name="end_time",
            new_name="clock_out_time",
        ),
        migrations.RenameField(
            model_name="staffrecordmodel",
            old_name="start_time",
            new_name="clock_in_time",
        ),
        migrations.RenameField(
            model_name="staffrecordmodel",
            old_name="end_time",
            new_name="clock_out_time",
        ),
    ]
