# Generated by Django 5.1.3 on 2026-01-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_customerrecordmodel_work_status_change_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerrecordmodel",
            name="work_status_change_history",
        ),
        migrations.RemoveField(
            model_name="staffrecordmodel",
            name="work_status_change_history",
        ),
        migrations.AddField(
            model_name="customerrecordmodel",
            name="is_work_status_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customersessionpatternmodel",
            name="is_end_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customersessionpatternmodel",
            name="is_place_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customersessionpatternmodel",
            name="is_start_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customersessionrecordmodel",
            name="is_end_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customersessionrecordmodel",
            name="is_place_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customersessionrecordmodel",
            name="is_start_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffrecordmodel",
            name="is_work_status_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffsessionpatternmodel",
            name="is_end_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffsessionpatternmodel",
            name="is_place_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffsessionpatternmodel",
            name="is_start_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffsessionrecordmodel",
            name="is_end_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffsessionrecordmodel",
            name="is_place_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffsessionrecordmodel",
            name="is_start_time_changed",
            field=models.BooleanField(default=False),
        ),
    ]
