# Generated by Django 5.1.3 on 2026-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_start_time_customerrecordmodel_clock_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerrecordmodel",
            name="current_status",
            field=models.IntegerField(
                choices=[
                    (0, "出勤前 / 通所前"),
                    (1, "勤務中"),
                    (5, "退勤済"),
                    (8, "在宅"),
                    (9, "休み"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="staffrecordmodel",
            name="current_status",
            field=models.IntegerField(
                choices=[
                    (0, "出勤前 / 通所前"),
                    (1, "勤務中"),
                    (5, "退勤済"),
                    (8, "在宅"),
                    (9, "休み"),
                ],
                default=0,
            ),
        ),
    ]
