# Generated by Django 5.1.3 on 2026-01-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_customerrecordmodel_work_status_change_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportrecordmodel",
            name="is_place_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transportrecordmodel",
            name="is_remarks_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transportrecordmodel",
            name="is_staff_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transportrecordmodel",
            name="is_time_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transportrecordmodel",
            name="is_transport_means_changed",
            field=models.BooleanField(default=False),
        ),
    ]
