# Generated by Django 5.1.3 on 2026-01-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_transportrecordmodel_is_place_changed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transportrecordmodel",
            old_name="is_place_changed",
            new_name="is_changed",
        ),
        migrations.RemoveField(
            model_name="transportrecordmodel",
            name="is_remarks_changed",
        ),
        migrations.RemoveField(
            model_name="transportrecordmodel",
            name="is_staff_changed",
        ),
        migrations.RemoveField(
            model_name="transportrecordmodel",
            name="is_time_changed",
        ),
        migrations.RemoveField(
            model_name="transportrecordmodel",
            name="is_transport_means_changed",
        ),
    ]
