# Generated by Django 5.1.3 on 2026-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_customerrecordmodel_current_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                ("notice", models.TextField(blank=True, default="", max_length=200)),
            ],
        ),
    ]
