# Generated by Django 5.1.3 on 2026-01-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0011_rename_is_place_changed_transportrecordmodel_is_changed_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customersessionpatternmodel",
            old_name="is_end_time_changed",
            new_name="is_changed",
        ),
        migrations.RenameField(
            model_name="customersessionrecordmodel",
            old_name="is_end_time_changed",
            new_name="is_changed",
        ),
        migrations.RenameField(
            model_name="staffsessionpatternmodel",
            old_name="is_end_time_changed",
            new_name="is_changed",
        ),
        migrations.RenameField(
            model_name="staffsessionrecordmodel",
            old_name="is_end_time_changed",
            new_name="is_changed",
        ),
        migrations.RemoveField(
            model_name="customersessionpatternmodel",
            name="is_place_changed",
        ),
        migrations.RemoveField(
            model_name="customersessionpatternmodel",
            name="is_start_time_changed",
        ),
        migrations.RemoveField(
            model_name="customersessionrecordmodel",
            name="is_place_changed",
        ),
        migrations.RemoveField(
            model_name="customersessionrecordmodel",
            name="is_start_time_changed",
        ),
        migrations.RemoveField(
            model_name="staffsessionpatternmodel",
            name="is_place_changed",
        ),
        migrations.RemoveField(
            model_name="staffsessionpatternmodel",
            name="is_start_time_changed",
        ),
        migrations.RemoveField(
            model_name="staffsessionrecordmodel",
            name="is_place_changed",
        ),
        migrations.RemoveField(
            model_name="staffsessionrecordmodel",
            name="is_start_time_changed",
        ),
    ]
