# Generated by Django 5.1.3 on 2026-01-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0012_rename_is_end_time_changed_customersessionpatternmodel_is_changed_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customersessionpatternmodel",
            name="is_changed",
        ),
        migrations.RemoveField(
            model_name="staffsessionpatternmodel",
            name="is_changed",
        ),
    ]
