# Generated by Django 5.1.3 on 2026-03-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_placeremarksmodel_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeremarksmodel",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
