# Generated by Django 5.1.3 on 2026-01-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_customersessionpatternmodel_is_changed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customersessionrecordmodel",
            old_name="is_changed",
            new_name="is_place_changed",
        ),
        migrations.AddField(
            model_name="customersessionrecordmodel",
            name="is_time_changed",
            field=models.BooleanField(default=False),
        ),
    ]
