# Generated by Django 5.1.3 on 2026-01-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0015_rename_is_changed_staffsessionrecordmodel_is_place_changed_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerrecordmodel",
            old_name="is_work_status_changed",
            new_name="is_work_status_changed_today",
        ),
        migrations.RenameField(
            model_name="customersessionrecordmodel",
            old_name="is_place_changed",
            new_name="is_place_changed_today",
        ),
        migrations.RenameField(
            model_name="customersessionrecordmodel",
            old_name="is_time_changed",
            new_name="is_time_changed_today",
        ),
        migrations.RenameField(
            model_name="staffrecordmodel",
            old_name="is_work_status_changed",
            new_name="is_work_status_changed_today",
        ),
        migrations.RenameField(
            model_name="staffsessionrecordmodel",
            old_name="is_place_changed",
            new_name="is_place_changed_today",
        ),
        migrations.RenameField(
            model_name="staffsessionrecordmodel",
            old_name="is_time_changed",
            new_name="is_time_changed_today",
        ),
        migrations.RenameField(
            model_name="transportrecordmodel",
            old_name="is_changed",
            new_name="is_changed_today",
        ),
    ]
