# Generated by Django 5.1.3 on 2026-01-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0016_rename_is_work_status_changed_customerrecordmodel_is_work_status_changed_today_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="OperationLogModel",
        ),
    ]
